import type { Metadata } from "next";
import SessionWrapper from "session-wrapper";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "./context/SessionContext";
import WebNavBar from "./components/nav/webNavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionWrapper>
        <SessionProvider>
          <body className={inter.className}>
            <WebNavBar />
            {children}
          </body>
        </SessionProvider>
      </SessionWrapper>
    </html>
  );
}
